"""Pre-generate the V=60 systems once, so the scoring worker can stay lean.

`boundary_map` imports torch (and the package `deepfeatselect` imports keras),
costing ~560 MB of resident memory that the CCM/PCMCI computation never uses.
The first V=60 attempt died of an out-of-memory on a 1 MB allocation, so that
560 MB is worth removing.

This script pays the torch import once, writes the systems to disk, and
exits, returning the memory to the OS. scripts/ccm_pcmci_v60.py then loads
the arrays and imports neither torch nor tensorflow.

The systems are generated by boundary_map.make_system with the same
arguments as before, so they remain byte-identical to the ones behind the
published boundary-map cells. An integrity hash is stored alongside each so
the worker can prove it loaded what was generated.

    python scripts/v60_gen_systems.py
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from boundary_map import make_system  # noqa: E402  (pulls torch; that is why
#                                        this lives in its own process)

OUT = Path("ExpOutput/ccm_pcmci_v60")
N, V, COUPLING, REDUNDANCY = 4000, 60, 0.20, 0
SEEDS = (0, 1, 2)


def true_parents(V: int, seed: int) -> tuple[np.ndarray, int]:
    """Replay make_system's rng draws in order to recover parent[]."""
    rng = np.random.default_rng(seed)
    n_src = max(3, V // 6)
    n_drv = V - n_src
    rng.uniform(0.2, 0.8, V)      # x[0]
    rng.uniform(3.6, 3.9, V)      # r
    return rng.integers(0, n_src, n_drv), n_src


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        x, is_driven, is_source = make_system(
            n=N, V=V, coupling=COUPLING, redundancy=REDUNDANCY, seed=seed)
        parent, n_src = true_parents(V, seed)
        src_idx, drv_idx = np.where(is_source)[0], np.where(is_driven)[0]
        true_edge = np.zeros((V, V), bool)
        for k, p in enumerate(parent):
            true_edge[src_idx[p], drv_idx[k]] = True

        digest = hashlib.sha256(np.ascontiguousarray(x)).hexdigest()[:16]
        f = OUT / f"system_s{seed}.npz"
        np.savez_compressed(f, x=x, is_driven=is_driven, is_source=is_source,
                            true_edge=true_edge, sha=digest)
        print(f"  seed {seed}: {x.shape} sources={is_source.sum()} "
              f"driven={is_driven.sum()} edges={true_edge.sum()} "
              f"sha={digest}  -> {f.name}")
    print("\nsystems written; the scoring worker needs no torch import.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
